[package]
name = "rust-2d-demo"
version = "0.1.0"
authors = ["Jason Dagit <dagitj@gmail.com>"]

[profile.dev]
opt-level = 2
debug     = true

[dependencies]
glium      = "*"
glutin     = "*"
rusttype   = "*"
immi       = "*"
image      = "*"


